name: Mise à jour du débit de l'Isère

on:
  schedule:
    - cron: '0 * * * *'  # toutes les heures
  workflow_dispatch:     # exécutable manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v4

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: pip install -r requirements.txt

    - name: Exécuter le script Python
      run: python scripts/fetch_debit.py

    - name: Commit et push si changement
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs/debit_isere.md
        git commit -m "Mise à jour automatique du débit" || echo "Pas de changement"
        git push
