nav:
    - Accueil: index.md

    - Le Parlement: pages/le_parlement/presentation_parlement.md

    - Documentation:
        - Etudes & Rapports: pages/documentation/etudes_rapports.md
        - Articles de presse: pages/documentation/article_presse.md
        - Vidéos & Podcasts: pages/documentation/videos_podcast.md

    - Nous contacter: pages/contact.md




site_name: Parlement de la rivière Isère
site_author: Nicolas Brémond
site_description: A l'écoute de la rivière et de ses affluents.
site_url: https://konsilion.github.io/website-parlement-riviere-isere
repo_url: https://github.com/konsilion/website-parlement-riviere-isere
repo_name: konsilion/website-parlement-riviere-isere
edit_uri: edit/master/mkdocs/docs/

extra:
    generator: false
  
theme:
    name: material
    palette:
        primary: blue grey
        accent: blue
    logo: https://github.com/Konsilion/website-parlement-riviere-isere/blob/master/mkdocs/media/logo-blanc-flaticon-PRI.png?raw=true
    favicon: https://github.com/Konsilion/website-parlement-riviere-isere/blob/master/mkdocs/media/logo-parlement-isere.png?raw=true
    features:
      - navigation.indexes
      - navigation.tracking
      - navigation.top
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.expand
    language: fr
      
plugins:
  - macros
  - search
  - mkdocs-video
  - tags

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
  - personnel.css
  - https://konsilion.github.io/katalog-setup/css/konsilion-mkdocs.css

copyright: Une plateforme développée avec ❤ par Nicolas Brémond pour le Collectif du Parlement de la rivière Isère.
