# BIENVENU ! MODIFIER ICI LES PARAMETRES DE VOTRE PLATEFORME KATALOG
# -------------------------------------------------


# NAVIGATION
# -------------------------------------------------

nav:

    - Acceuil: index.md

    - Le Parlement:
        - pages/le_parlement/presentation_parlement.md
        - pages/le_parlement/collectif/qui_sommes-nous.md

    - Observatoire de l'eau:
        - La documentation: pages/documentation.md
        - Les données: pages/donnees.md
    
    - Actualités:
        - actualite/index.md

    - Nous contacter: pages/contact.md



# SITE INFORMATIONS 
# -------------------------------------------------

site_name: Parlement de la rivière Isère
site_author: Nicolas Brémond
site_description: A l'écoute de la rivière et de ses affluents.
repo_url: https://github.com/konsilion/website-parlement-riviere-isere

extra:
  katalog_repo: "https://github.com/Konsilion/website-parlement-riviere-isere"
  katalog_site: ""
  katalog_mdp: "azerty123"
  


# /!\   NE PAS MODIFIER CI-DESSOUS   /!\
# -------------------------------------------------
theme:
    name: material
    language: fr
    palette:
        primary: blue grey
        accent: blue
    logo: https://github.com/Konsilion/website-parlement-riviere-isere/blob/master/mkdocs/media/logo-blanc-flaticon-PRI.png?raw=true
    favicon: https://github.com/Konsilion/website-parlement-riviere-isere/blob/master/mkdocs/media/logo-parlement-isere.png?raw=true
    features:
      - navigation.indexes
      - navigation.tracking
      - navigation.top
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.expand
      
extra:
  generator: false

plugins:
  - macros
  - tags
  - search
  - blog:
        blog_dir: actualite
        archive: true
        post_readtime_words_per_minute: 390
        blog_toc: false
        archive_name: Chronologie
        archive_toc: true
        categories_name: Thématiques
        categories_toc: true
        categories_allowed:
            - Evenement
            - Gouvernance
            - Documentation
            - Données

# MENTIONS 
# -------------------------------------------------

copyright: Une plateforme sobre et pleine de ❤ - <u><a href="https://www.konsilion.fr/" target="_blank">Konsilion</a></u> - Licence juridique Creative Commons CC-BY-NC

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - https://konsilion.github.io/katalog-setup/css/konsilion-mkdocs.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css
  - css/colors.css
