# BIENVENU ! MODIFIER ICI LES PARAMETRES DE VOTRE PLATEFORME KATALOG
# -------------------------------------------------


# NAVIGATION
# -------------------------------------------------

nav:

    - Accueil: index.md
        
    - Le Parlement: pages/qui-sommes-nous.md

    - Documentation: pages/documentation/accueil.md

    - Données: pages/donnees/index.md

    - Actualités:
        - actualite/index.md

    - Contact: pages/contact.md



# SITE INFORMATIONS 
# -------------------------------------------------

site_name: Parlement de la rivière Isère
site_author: Nicolas Brémond
site_description: A l'écoute de la rivière et de ses affluents.
repo_url: https://github.com/konsilion/website-parlement-riviere-isere

extra:
  katalog_repo: "https://github.com/Konsilion/website-parlement-riviere-isere"
  katalog_site: ""
  katalog_mdp: "azerty123"
  

# LANGUE, COULEURS et LOGO
#
# [Liste des couleurs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)
# -------------------------------------------------

theme:
    language: fr
    palette:
        primary: blue grey
        accent: blue
    logo: https://github.com/Konsilion/website-parlement-riviere-isere/blob/master/mkdocs/media/banniere-parlement-isere.png?raw=true
    favicon: https://github.com/Konsilion/website-parlement-riviere-isere/blob/master/mkdocs/media/logo-parlement-isere.png?raw=true


# /!\   NE PAS MODIFIER CI-DESSOUS   /!\
# -------------------------------------------------
INHERIT: ./docs/admin/env
