nav:
    - Accueil: index.md

    - Le Parlement: pages/le_parlement/presentation_parlement.md

    - Les Commissions : 
        - pages/commissions/index.md
        - Démocratique : pages/commissions/democratie/contact.md
        - Juridique : pages/commissions/juridique/contact.md
        - Artistique : 
            - Galerie d'image : pages/commissions/artistique/images.md
            - Contact : pages/commissions/artistique/contact.md
        - Scientifique : pages/commissions/scientifique/contact.md

    - Documentation partagée : 
        - pages/documentation/index.md
        - Comprendre la gestion de l'eau ? : pages/commissions/scientifique/cartes_mentales/gestion.md
            
    - Nous contacter: pages/contact.md






site_name: Parlement de la rivière Isère
site_author: Nicolas Brémond
site_description: Ecouter la rivière et ses affluents.
site_url: https://konsilion.github.io/website-parlement-riviere-isere
repo_url: https://github.com/konsilion/website-parlement-riviere-isere
repo_name: konsilion/website-parlement-riviere-isere
edit_uri: edit/master/mkdocs/docs/

extra:
    generator: false

theme:
    name: material
    features:
      - content.action.edit
      - navigation.indexes
      - navigation.tracking
      - navigation.top
      - navigation.tabs
      - navigation.tabs.sticky
    language: fr
    palette:
        primary: blue grey
        accent: blue
    logo: https://github.com/Konsilion/website-parlement-riviere-isere/blob/master/mkdocs/media/logo-blanc-flaticon-PRI.png?raw=true
    favicon: https://github.com/Konsilion/website-parlement-riviere-isere/blob/master/mkdocs/media/logo-parlement-isere.png?raw=true
    
plugins:
  - macros
  - mkdocs-video

markdown_extensions:
  - toc:
      toc_depth: 2
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes


extra_css:
  - personnel.css

copyright: Une plateforme développée avec ❤ par Nicolas Brémond pour le Collectif du Parlement de la rivière Isère. Made with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank">Material for MkDocs Insiders</a>
