site_name: Parlement de la rivière Isère
site_author: Nicolas Brémond
site_description: Ecouter la rivière et ses affluents.
site_url: https://parlement-isere.org
repo_url: https://github.com/konsilion/website-parlement-riviere-isere
repo_name: konsilion/website-parlement-riviere-isere
edit_uri: edit/master/mkdocs/docs/

nav:
    - Accueil: index.md

    - Le Parlement: pages/le_parlement/index.md

    - La Démarche: pages/la_demarche/index.md

    - Les Commissions : 
        - Accueil: pages/commissions/index.md
        - Démocratique : pages/commissions/democratie/contact.md
        - Juridique : pages/commissions/juridique/contact.md
        - Artistique :
            - pages/commissions/artistique/index.md
            - Galerie d'images : pages/commissions/artistique/images.md
        - Scientifique : 
            - pages/commissions/scientifique/index.md
            - Prises de notes : pages/commissions/scientifique/prise_note.md

    - Les Sessions :
        - pages/sessions/index.md
        - Première session : pages/sessions/premiere_session.md
        - Deuxième session : pages/sessions/deuxieme_session.md
        - Troisième session : pages/sessions/troisieme_session.md

    - Gardien·nes : pages/gardiennes/index.md

    - Actualités : pages/actualites/index.md

    - Ressources :
        - Accueil: pages/ressources/index.md
        - Presse : pages/ressources/presse.md
        - Sur les bords de l'Isère : pages/ressources/bords_isere.md
        - Usages et gestion des eaux : pages/ressources/usages_gestion_eau.md

    - Contact : pages/contact.md

extra:
    generator: false
    social:
      - icon: fontawesome/brands/facebook
        link: https://www.facebook.com/people/Parlement-de-lIs%C3%A8re/61557683175720/
      - icon: fontawesome/brands/instagram
        link: https://www.instagram.com/parlement_isere/
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/company/parlement-de-la-rivi%C3%A8re-is%C3%A8re

theme:
    name: material
    features:
      - content.action.edit
      - navigation.indexes
      - navigation.tracking
      - navigation.expand
      - navigation.top
      - navigation.tabs
      - navigation.tabs.sticky
    language: fr
    palette:
        primary: blue grey
        accent: blue
    logo: https://github.com/Konsilion/website-parlement-riviere-isere/blob/master/mkdocs/media/logo-blanc-flaticon-PRI.png?raw=true
    favicon: https://github.com/Konsilion/website-parlement-riviere-isere/blob/master/mkdocs/media/logo-parlement-isere.png?raw=true
    
plugins:
  - macros
  - mkdocs-video

markdown_extensions:
  - toc:
      toc_depth: 2
  - tables
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg



extra_css:
  - personnel.css

copyright: Un site web développé avec ❤ par Nicolas Brémond pour le Collectif du Parlement de la rivière Isère. Made with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank">Material for MkDocs</a>
